

set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CMAKE_SYSTEM_NAME Linux)

set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)

if(PORT STREQUAL "ftxui")
    list(APPEND VCPKG_CMAKE_CONFIGURE_OPTIONS "-DFTXUI_BUILD_MODULES=ON")
endif()